version: '3.9'

services:
  web:
    build: .
    command: >
      bash -c "python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              ln -s /usr/local/lib/python3.12/site-packages/oscar/static/oscar/img/image_not_found.jpg /usr/src/shopping-online-tour/media/ &&
              gunicorn shopping_online_tour.wsgi:application -c gunicorn_co
    restart: always
    volumes:
      - ./media/:/usr/src/shopping-online-tour/media/
      - ./staticfiles/:/usr/src/shopping-online-tour/staticfiles/
      - /var/certbot/conf:/etc/letsencrypt/:ro
    expose:
      - 8080
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    volumes:
      - ./:/usr/src/shopping-online-tour
      - ./media/:/usr/src/shopping-online-tour/media/
      - ./staticfiles/:/usr/src/shopping-online-tour/staticfiles/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /var/certbot/conf:/etc/letsencrypt/:rw
      - /var/certbot/www/:/var/www/certbot/:rw
    depends_on:
      - nginx
volumes:
  postgres_data:
