# Generated by Django 4.2.7 on 2024-01-17 13:29

from django.db import migrations, models
import oscar.models.fields.slugfield


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0026_predefined_product_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Meta description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="categories",
                        verbose_name="Image",
                    ),
                ),
                (
                    "slug",
                    oscar.models.fields.slugfield.SlugField(
                        max_length=255, verbose_name="Slug"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Show this category in search results and catalogue listings.",
                        verbose_name="Is public",
                    ),
                ),
                (
                    "ancestors_are_public",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="The ancestors of this category are public",
                        verbose_name="Ancestor categories are public",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["path"],
                "abstract": False,
            },
        ),
    ]
