# Generated by Django 4.2.7 on 2024-01-26 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0027_abstractcategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AbstractCategory",
        ),
    ]
