# Generated by Django 4.2.7 on 2024-01-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0028_delete_abstractcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="keywords",
            field=models.TextField(blank=True, verbose_name="keywords"),
        ),
    ]
