# Generated by Django 4.2.7 on 2024-01-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0029_category_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="keywords",
            field=models.TextField(blank=True, verbose_name="keywords"),
        ),
    ]
