# Generated by Django 4.2.7 on 2024-02-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0030_product_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(blank=True, max_length=355, verbose_name="Title"),
        ),
    ]
