# Generated by Django 4.2.7 on 2024-02-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0032_alter_product_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(blank=True, max_length=1000, verbose_name="Title"),
        ),
    ]
